# Build Configuration  ############################

build:
  version: <<build.version>>

# Server Configuration ############################

server:
  port: 8090
  compression:
    enabled: true
    min-response-size: 2048
    # Comma-separated list of MIME types that should be compressed.
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/xml,application/javascript
  servlet:
    contextPath: /
    session:
      timeout: 1h
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

# Spring Configuration ############################

spring:
  main:
    banner-mode: console
    allow-bean-definition-overriding: false
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: false


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    #jdbcUrl: jdbc:h2:mem:testdb
    #jdbcUrl: jdbc:h2:${app.home}/data/db/h2/digitaldb
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

# Log Configuration ###########################

logging:
  config: classpath:logback-console.xml

# Hibernate And DB  Configuration #######################

hibernate:
  jdbc:
    batch_size: 30
    batch_versioned_data: true
  order_inserts: true
  order_updates: true
  show_sql: false
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: update



---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    #jdbcUrl: jdbc:h2:mem:testdb
    #jdbcUrl: jdbc:h2:${app.home}/data/db/h2/digital
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: data

app:
  data:
    init-sample: true
    init-demo: false

---
spring:
  config:
    activate:
      on-profile: hsql
  datasource:
    url: jdbc:hsqldb:mem:digital
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    #jdbcUrl: jdbc:postgresql://localhost:5432/digitaldb
    url: jdbc:postgresql://localhost:5432/digitaldb
    username: devteam
    password: devteam
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: daemon

logging:
  config: classpath:logback-file.xml

---
spring:
  config:
    activate:
      on-profile: production

hibernate:
  hbm2ddl:
    auto: validate

logging:
  config: classpath:logback-file.xml

---
spring:
  config:
    activate:
      on-profile: flyway
  main:
    web-application-type: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0.0

hibernate:
  hbm2ddl:
    auto: update
---
spring:
  config:
    activate:
      on-profile: debug

logging:
  config: classpath:logback-console-debug.xml

---
spring:
  config:
    activate:
      on-profile: debug-all

logging:
  config: classpath:logback-console-debug-all.xml
